// Auto-generated by mujoco-react. Do not edit.
// Regenerate by running Vite with the mujocoReact() plugin or `mujoco-react codegen`.

import { registerRobotResources } from 'mujoco-react';
import type { RobotResource } from 'mujoco-react';

type GeneratedRobotResources = {
  readonly franka: {
    readonly actuators: {
      readonly actuator1: 'actuator1';
      readonly actuator2: 'actuator2';
      readonly actuator3: 'actuator3';
      readonly actuator4: 'actuator4';
      readonly actuator5: 'actuator5';
      readonly actuator6: 'actuator6';
      readonly actuator7: 'actuator7';
      readonly gripper: 'gripper';
    };
    readonly sensors: {};
    readonly bodies: {
      readonly hand: 'hand';
      readonly left_finger: 'left_finger';
      readonly link0: 'link0';
      readonly link1: 'link1';
      readonly link2: 'link2';
      readonly link3: 'link3';
      readonly link4: 'link4';
      readonly link5: 'link5';
      readonly link6: 'link6';
      readonly link7: 'link7';
      readonly right_finger: 'right_finger';
    };
    readonly joints: {
      readonly finger_joint1: 'finger_joint1';
      readonly finger_joint2: 'finger_joint2';
      readonly joint1: 'joint1';
      readonly joint2: 'joint2';
      readonly joint3: 'joint3';
      readonly joint4: 'joint4';
      readonly joint5: 'joint5';
      readonly joint6: 'joint6';
      readonly joint7: 'joint7';
    };
    readonly sites: {
      readonly tcp: 'tcp';
    };
    readonly geoms: {
      readonly floor: 'floor';
    };
    readonly keyframes: {
      readonly home: 'home';
    };
    readonly cameras: {};
  };
  readonly so101: {
    readonly actuators: {
      readonly elbow_flex: 'elbow_flex';
      readonly gripper: 'gripper';
      readonly shoulder_lift: 'shoulder_lift';
      readonly shoulder_pan: 'shoulder_pan';
      readonly wrist_flex: 'wrist_flex';
      readonly wrist_roll: 'wrist_roll';
    };
    readonly sensors: {};
    readonly bodies: {
      readonly base: 'base';
      readonly camera_mount: 'camera_mount';
      readonly gripper: 'gripper';
      readonly lower_arm: 'lower_arm';
      readonly moving_jaw_so101_v1: 'moving_jaw_so101_v1';
      readonly shoulder: 'shoulder';
      readonly upper_arm: 'upper_arm';
      readonly wrist: 'wrist';
    };
    readonly joints: {
      readonly elbow_flex: 'elbow_flex';
      readonly gripper: 'gripper';
      readonly shoulder_lift: 'shoulder_lift';
      readonly shoulder_pan: 'shoulder_pan';
      readonly wrist_flex: 'wrist_flex';
      readonly wrist_roll: 'wrist_roll';
    };
    readonly sites: {
      readonly baseframe: 'baseframe';
      readonly gripperframe: 'gripperframe';
    };
    readonly geoms: {
      readonly camera_box1: 'camera_box1';
      readonly camera_box2: 'camera_box2';
      readonly fixed_jaw_box1: 'fixed_jaw_box1';
      readonly fixed_jaw_box2: 'fixed_jaw_box2';
      readonly fixed_jaw_box3: 'fixed_jaw_box3';
      readonly fixed_jaw_box4: 'fixed_jaw_box4';
      readonly fixed_jaw_box5: 'fixed_jaw_box5';
      readonly fixed_jaw_box6: 'fixed_jaw_box6';
      readonly fixed_jaw_box7: 'fixed_jaw_box7';
      readonly fixed_jaw_sph_tip1: 'fixed_jaw_sph_tip1';
      readonly fixed_jaw_sph_tip2: 'fixed_jaw_sph_tip2';
      readonly fixed_jaw_sph_tip3: 'fixed_jaw_sph_tip3';
      readonly moving_jaw_box1: 'moving_jaw_box1';
      readonly moving_jaw_box2: 'moving_jaw_box2';
      readonly moving_jaw_box3: 'moving_jaw_box3';
      readonly moving_jaw_sph_tip1: 'moving_jaw_sph_tip1';
      readonly moving_jaw_sph_tip2: 'moving_jaw_sph_tip2';
      readonly moving_jaw_sph_tip3: 'moving_jaw_sph_tip3';
    };
    readonly keyframes: {};
    readonly cameras: {
      readonly wrist_cam: 'wrist_cam';
    };
  };
  readonly xlerobot: {
    readonly actuators: {
      readonly Elbow_L: 'Elbow_L';
      readonly Elbow_R: 'Elbow_R';
      readonly forward: 'forward';
      readonly head_pan: 'head_pan';
      readonly head_tilt: 'head_tilt';
      readonly Jaw_L: 'Jaw_L';
      readonly Jaw_R: 'Jaw_R';
      readonly Pitch_L: 'Pitch_L';
      readonly Pitch_R: 'Pitch_R';
      readonly Rotation_L: 'Rotation_L';
      readonly Rotation_R: 'Rotation_R';
      readonly turn: 'turn';
      readonly Wrist_Pitch_L: 'Wrist_Pitch_L';
      readonly Wrist_Pitch_R: 'Wrist_Pitch_R';
      readonly Wrist_Roll_L: 'Wrist_Roll_L';
      readonly Wrist_Roll_R: 'Wrist_Roll_R';
    };
    readonly sensors: {};
    readonly bodies: {
      readonly Base: 'Base';
      readonly Base_2: 'Base_2';
      readonly chassis: 'chassis';
      readonly Fixed_Jaw: 'Fixed_Jaw';
      readonly Fixed_Jaw_2: 'Fixed_Jaw_2';
      readonly head_pan_link: 'head_pan_link';
      readonly head_tilt_link: 'head_tilt_link';
      readonly Left_Arm_Camera: 'Left_Arm_Camera';
      readonly left_wheel: 'left_wheel';
      readonly Lower_Arm: 'Lower_Arm';
      readonly Lower_Arm_2: 'Lower_Arm_2';
      readonly Moving_Jaw: 'Moving_Jaw';
      readonly Moving_Jaw_2: 'Moving_Jaw_2';
      readonly Right_Arm_Camera: 'Right_Arm_Camera';
      readonly right_wheel: 'right_wheel';
      readonly Rotation_Pitch: 'Rotation_Pitch';
      readonly Rotation_Pitch_2: 'Rotation_Pitch_2';
      readonly top_base_link: 'top_base_link';
      readonly Upper_Arm: 'Upper_Arm';
      readonly Upper_Arm_2: 'Upper_Arm_2';
      readonly Wrist_Pitch_Roll: 'Wrist_Pitch_Roll';
      readonly Wrist_Pitch_Roll_2: 'Wrist_Pitch_Roll_2';
    };
    readonly joints: {
      readonly Elbow_L: 'Elbow_L';
      readonly Elbow_R: 'Elbow_R';
      readonly head_pan_joint: 'head_pan_joint';
      readonly head_tilt_joint: 'head_tilt_joint';
      readonly Jaw_L: 'Jaw_L';
      readonly Jaw_R: 'Jaw_R';
      readonly left_wheel_joint: 'left_wheel_joint';
      readonly Pitch_L: 'Pitch_L';
      readonly Pitch_R: 'Pitch_R';
      readonly right_wheel_joint: 'right_wheel_joint';
      readonly Rotation_L: 'Rotation_L';
      readonly Rotation_R: 'Rotation_R';
      readonly Wrist_Pitch_L: 'Wrist_Pitch_L';
      readonly Wrist_Pitch_R: 'Wrist_Pitch_R';
      readonly Wrist_Roll_L: 'Wrist_Roll_L';
      readonly Wrist_Roll_R: 'Wrist_Roll_R';
    };
    readonly sites: {};
    readonly geoms: {
      readonly back_caster: 'back_caster';
      readonly front_caster: 'front_caster';
    };
    readonly keyframes: {};
    readonly cameras: {
      readonly dock_cam: 'dock_cam';
    };
  };
  readonly spot: {
    readonly actuators: {
      readonly fl_hx: 'fl_hx';
      readonly fl_hy: 'fl_hy';
      readonly fl_kn: 'fl_kn';
      readonly fr_hx: 'fr_hx';
      readonly fr_hy: 'fr_hy';
      readonly fr_kn: 'fr_kn';
      readonly hl_hx: 'hl_hx';
      readonly hl_hy: 'hl_hy';
      readonly hl_kn: 'hl_kn';
      readonly hr_hx: 'hr_hx';
      readonly hr_hy: 'hr_hy';
      readonly hr_kn: 'hr_kn';
    };
    readonly sensors: {};
    readonly bodies: {
      readonly body: 'body';
      readonly fl_hip: 'fl_hip';
      readonly fl_lleg: 'fl_lleg';
      readonly fl_uleg: 'fl_uleg';
      readonly fr_hip: 'fr_hip';
      readonly fr_lleg: 'fr_lleg';
      readonly fr_uleg: 'fr_uleg';
      readonly hl_hip: 'hl_hip';
      readonly hl_lleg: 'hl_lleg';
      readonly hl_uleg: 'hl_uleg';
      readonly hr_hip: 'hr_hip';
      readonly hr_lleg: 'hr_lleg';
      readonly hr_uleg: 'hr_uleg';
    };
    readonly joints: {
      readonly fl_hx: 'fl_hx';
      readonly fl_hy: 'fl_hy';
      readonly fl_kn: 'fl_kn';
      readonly fr_hx: 'fr_hx';
      readonly fr_hy: 'fr_hy';
      readonly fr_kn: 'fr_kn';
      readonly hl_hx: 'hl_hx';
      readonly hl_hy: 'hl_hy';
      readonly hl_kn: 'hl_kn';
      readonly hr_hx: 'hr_hx';
      readonly hr_hy: 'hr_hy';
      readonly hr_kn: 'hr_kn';
    };
    readonly sites: {};
    readonly geoms: {
      readonly FL: 'FL';
      readonly floor: 'floor';
      readonly FR: 'FR';
      readonly HL: 'HL';
      readonly HR: 'HR';
    };
    readonly keyframes: {
      readonly home: 'home';
    };
    readonly cameras: {};
  };
  readonly g1: {
    readonly actuators: {
      readonly left_ankle_pitch_joint: 'left_ankle_pitch_joint';
      readonly left_ankle_roll_joint: 'left_ankle_roll_joint';
      readonly left_elbow_joint: 'left_elbow_joint';
      readonly left_hip_pitch_joint: 'left_hip_pitch_joint';
      readonly left_hip_roll_joint: 'left_hip_roll_joint';
      readonly left_hip_yaw_joint: 'left_hip_yaw_joint';
      readonly left_knee_joint: 'left_knee_joint';
      readonly left_shoulder_pitch_joint: 'left_shoulder_pitch_joint';
      readonly left_shoulder_roll_joint: 'left_shoulder_roll_joint';
      readonly left_shoulder_yaw_joint: 'left_shoulder_yaw_joint';
      readonly left_wrist_pitch_joint: 'left_wrist_pitch_joint';
      readonly left_wrist_roll_joint: 'left_wrist_roll_joint';
      readonly left_wrist_yaw_joint: 'left_wrist_yaw_joint';
      readonly right_ankle_pitch_joint: 'right_ankle_pitch_joint';
      readonly right_ankle_roll_joint: 'right_ankle_roll_joint';
      readonly right_elbow_joint: 'right_elbow_joint';
      readonly right_hip_pitch_joint: 'right_hip_pitch_joint';
      readonly right_hip_roll_joint: 'right_hip_roll_joint';
      readonly right_hip_yaw_joint: 'right_hip_yaw_joint';
      readonly right_knee_joint: 'right_knee_joint';
      readonly right_shoulder_pitch_joint: 'right_shoulder_pitch_joint';
      readonly right_shoulder_roll_joint: 'right_shoulder_roll_joint';
      readonly right_shoulder_yaw_joint: 'right_shoulder_yaw_joint';
      readonly right_wrist_pitch_joint: 'right_wrist_pitch_joint';
      readonly right_wrist_roll_joint: 'right_wrist_roll_joint';
      readonly right_wrist_yaw_joint: 'right_wrist_yaw_joint';
      readonly waist_pitch_joint: 'waist_pitch_joint';
      readonly waist_roll_joint: 'waist_roll_joint';
      readonly waist_yaw_joint: 'waist_yaw_joint';
    };
    readonly sensors: {
      readonly 'imu-pelvis-angular-velocity': 'imu-pelvis-angular-velocity';
      readonly 'imu-pelvis-linear-acceleration': 'imu-pelvis-linear-acceleration';
      readonly 'imu-torso-angular-velocity': 'imu-torso-angular-velocity';
      readonly 'imu-torso-linear-acceleration': 'imu-torso-linear-acceleration';
    };
    readonly bodies: {
      readonly left_ankle_pitch_link: 'left_ankle_pitch_link';
      readonly left_ankle_roll_link: 'left_ankle_roll_link';
      readonly left_elbow_link: 'left_elbow_link';
      readonly left_hip_pitch_link: 'left_hip_pitch_link';
      readonly left_hip_roll_link: 'left_hip_roll_link';
      readonly left_hip_yaw_link: 'left_hip_yaw_link';
      readonly left_knee_link: 'left_knee_link';
      readonly left_shoulder_pitch_link: 'left_shoulder_pitch_link';
      readonly left_shoulder_roll_link: 'left_shoulder_roll_link';
      readonly left_shoulder_yaw_link: 'left_shoulder_yaw_link';
      readonly left_wrist_pitch_link: 'left_wrist_pitch_link';
      readonly left_wrist_roll_link: 'left_wrist_roll_link';
      readonly left_wrist_yaw_link: 'left_wrist_yaw_link';
      readonly pelvis: 'pelvis';
      readonly right_ankle_pitch_link: 'right_ankle_pitch_link';
      readonly right_ankle_roll_link: 'right_ankle_roll_link';
      readonly right_elbow_link: 'right_elbow_link';
      readonly right_hip_pitch_link: 'right_hip_pitch_link';
      readonly right_hip_roll_link: 'right_hip_roll_link';
      readonly right_hip_yaw_link: 'right_hip_yaw_link';
      readonly right_knee_link: 'right_knee_link';
      readonly right_shoulder_pitch_link: 'right_shoulder_pitch_link';
      readonly right_shoulder_roll_link: 'right_shoulder_roll_link';
      readonly right_shoulder_yaw_link: 'right_shoulder_yaw_link';
      readonly right_wrist_pitch_link: 'right_wrist_pitch_link';
      readonly right_wrist_roll_link: 'right_wrist_roll_link';
      readonly right_wrist_yaw_link: 'right_wrist_yaw_link';
      readonly torso_link: 'torso_link';
      readonly waist_roll_link: 'waist_roll_link';
      readonly waist_yaw_link: 'waist_yaw_link';
    };
    readonly joints: {
      readonly left_ankle_pitch_joint: 'left_ankle_pitch_joint';
      readonly left_ankle_roll_joint: 'left_ankle_roll_joint';
      readonly left_elbow_joint: 'left_elbow_joint';
      readonly left_hip_pitch_joint: 'left_hip_pitch_joint';
      readonly left_hip_roll_joint: 'left_hip_roll_joint';
      readonly left_hip_yaw_joint: 'left_hip_yaw_joint';
      readonly left_knee_joint: 'left_knee_joint';
      readonly left_shoulder_pitch_joint: 'left_shoulder_pitch_joint';
      readonly left_shoulder_roll_joint: 'left_shoulder_roll_joint';
      readonly left_shoulder_yaw_joint: 'left_shoulder_yaw_joint';
      readonly left_wrist_pitch_joint: 'left_wrist_pitch_joint';
      readonly left_wrist_roll_joint: 'left_wrist_roll_joint';
      readonly left_wrist_yaw_joint: 'left_wrist_yaw_joint';
      readonly right_ankle_pitch_joint: 'right_ankle_pitch_joint';
      readonly right_ankle_roll_joint: 'right_ankle_roll_joint';
      readonly right_elbow_joint: 'right_elbow_joint';
      readonly right_hip_pitch_joint: 'right_hip_pitch_joint';
      readonly right_hip_roll_joint: 'right_hip_roll_joint';
      readonly right_hip_yaw_joint: 'right_hip_yaw_joint';
      readonly right_knee_joint: 'right_knee_joint';
      readonly right_shoulder_pitch_joint: 'right_shoulder_pitch_joint';
      readonly right_shoulder_roll_joint: 'right_shoulder_roll_joint';
      readonly right_shoulder_yaw_joint: 'right_shoulder_yaw_joint';
      readonly right_wrist_pitch_joint: 'right_wrist_pitch_joint';
      readonly right_wrist_roll_joint: 'right_wrist_roll_joint';
      readonly right_wrist_yaw_joint: 'right_wrist_yaw_joint';
      readonly waist_pitch_joint: 'waist_pitch_joint';
      readonly waist_roll_joint: 'waist_roll_joint';
      readonly waist_yaw_joint: 'waist_yaw_joint';
    };
    readonly sites: {
      readonly imu_in_pelvis: 'imu_in_pelvis';
      readonly imu_in_torso: 'imu_in_torso';
      readonly left_foot: 'left_foot';
      readonly right_foot: 'right_foot';
    };
    readonly geoms: {
      readonly floor: 'floor';
    };
    readonly keyframes: {
      readonly stand: 'stand';
    };
    readonly cameras: {};
  };
};

const generatedRobotResources: GeneratedRobotResources = {
  franka: {
    actuators: {
      actuator1: 'actuator1',
      actuator2: 'actuator2',
      actuator3: 'actuator3',
      actuator4: 'actuator4',
      actuator5: 'actuator5',
      actuator6: 'actuator6',
      actuator7: 'actuator7',
      gripper: 'gripper',
    },
    sensors: {},
    bodies: {
      hand: 'hand',
      left_finger: 'left_finger',
      link0: 'link0',
      link1: 'link1',
      link2: 'link2',
      link3: 'link3',
      link4: 'link4',
      link5: 'link5',
      link6: 'link6',
      link7: 'link7',
      right_finger: 'right_finger',
    },
    joints: {
      finger_joint1: 'finger_joint1',
      finger_joint2: 'finger_joint2',
      joint1: 'joint1',
      joint2: 'joint2',
      joint3: 'joint3',
      joint4: 'joint4',
      joint5: 'joint5',
      joint6: 'joint6',
      joint7: 'joint7',
    },
    sites: {
      tcp: 'tcp',
    },
    geoms: {
      floor: 'floor',
    },
    keyframes: {
      home: 'home',
    },
    cameras: {},
  },
  so101: {
    actuators: {
      elbow_flex: 'elbow_flex',
      gripper: 'gripper',
      shoulder_lift: 'shoulder_lift',
      shoulder_pan: 'shoulder_pan',
      wrist_flex: 'wrist_flex',
      wrist_roll: 'wrist_roll',
    },
    sensors: {},
    bodies: {
      base: 'base',
      camera_mount: 'camera_mount',
      gripper: 'gripper',
      lower_arm: 'lower_arm',
      moving_jaw_so101_v1: 'moving_jaw_so101_v1',
      shoulder: 'shoulder',
      upper_arm: 'upper_arm',
      wrist: 'wrist',
    },
    joints: {
      elbow_flex: 'elbow_flex',
      gripper: 'gripper',
      shoulder_lift: 'shoulder_lift',
      shoulder_pan: 'shoulder_pan',
      wrist_flex: 'wrist_flex',
      wrist_roll: 'wrist_roll',
    },
    sites: {
      baseframe: 'baseframe',
      gripperframe: 'gripperframe',
    },
    geoms: {
      camera_box1: 'camera_box1',
      camera_box2: 'camera_box2',
      fixed_jaw_box1: 'fixed_jaw_box1',
      fixed_jaw_box2: 'fixed_jaw_box2',
      fixed_jaw_box3: 'fixed_jaw_box3',
      fixed_jaw_box4: 'fixed_jaw_box4',
      fixed_jaw_box5: 'fixed_jaw_box5',
      fixed_jaw_box6: 'fixed_jaw_box6',
      fixed_jaw_box7: 'fixed_jaw_box7',
      fixed_jaw_sph_tip1: 'fixed_jaw_sph_tip1',
      fixed_jaw_sph_tip2: 'fixed_jaw_sph_tip2',
      fixed_jaw_sph_tip3: 'fixed_jaw_sph_tip3',
      moving_jaw_box1: 'moving_jaw_box1',
      moving_jaw_box2: 'moving_jaw_box2',
      moving_jaw_box3: 'moving_jaw_box3',
      moving_jaw_sph_tip1: 'moving_jaw_sph_tip1',
      moving_jaw_sph_tip2: 'moving_jaw_sph_tip2',
      moving_jaw_sph_tip3: 'moving_jaw_sph_tip3',
    },
    keyframes: {},
    cameras: {
      wrist_cam: 'wrist_cam',
    },
  },
  xlerobot: {
    actuators: {
      Elbow_L: 'Elbow_L',
      Elbow_R: 'Elbow_R',
      forward: 'forward',
      head_pan: 'head_pan',
      head_tilt: 'head_tilt',
      Jaw_L: 'Jaw_L',
      Jaw_R: 'Jaw_R',
      Pitch_L: 'Pitch_L',
      Pitch_R: 'Pitch_R',
      Rotation_L: 'Rotation_L',
      Rotation_R: 'Rotation_R',
      turn: 'turn',
      Wrist_Pitch_L: 'Wrist_Pitch_L',
      Wrist_Pitch_R: 'Wrist_Pitch_R',
      Wrist_Roll_L: 'Wrist_Roll_L',
      Wrist_Roll_R: 'Wrist_Roll_R',
    },
    sensors: {},
    bodies: {
      Base: 'Base',
      Base_2: 'Base_2',
      chassis: 'chassis',
      Fixed_Jaw: 'Fixed_Jaw',
      Fixed_Jaw_2: 'Fixed_Jaw_2',
      head_pan_link: 'head_pan_link',
      head_tilt_link: 'head_tilt_link',
      Left_Arm_Camera: 'Left_Arm_Camera',
      left_wheel: 'left_wheel',
      Lower_Arm: 'Lower_Arm',
      Lower_Arm_2: 'Lower_Arm_2',
      Moving_Jaw: 'Moving_Jaw',
      Moving_Jaw_2: 'Moving_Jaw_2',
      Right_Arm_Camera: 'Right_Arm_Camera',
      right_wheel: 'right_wheel',
      Rotation_Pitch: 'Rotation_Pitch',
      Rotation_Pitch_2: 'Rotation_Pitch_2',
      top_base_link: 'top_base_link',
      Upper_Arm: 'Upper_Arm',
      Upper_Arm_2: 'Upper_Arm_2',
      Wrist_Pitch_Roll: 'Wrist_Pitch_Roll',
      Wrist_Pitch_Roll_2: 'Wrist_Pitch_Roll_2',
    },
    joints: {
      Elbow_L: 'Elbow_L',
      Elbow_R: 'Elbow_R',
      head_pan_joint: 'head_pan_joint',
      head_tilt_joint: 'head_tilt_joint',
      Jaw_L: 'Jaw_L',
      Jaw_R: 'Jaw_R',
      left_wheel_joint: 'left_wheel_joint',
      Pitch_L: 'Pitch_L',
      Pitch_R: 'Pitch_R',
      right_wheel_joint: 'right_wheel_joint',
      Rotation_L: 'Rotation_L',
      Rotation_R: 'Rotation_R',
      Wrist_Pitch_L: 'Wrist_Pitch_L',
      Wrist_Pitch_R: 'Wrist_Pitch_R',
      Wrist_Roll_L: 'Wrist_Roll_L',
      Wrist_Roll_R: 'Wrist_Roll_R',
    },
    sites: {},
    geoms: {
      back_caster: 'back_caster',
      front_caster: 'front_caster',
    },
    keyframes: {},
    cameras: {
      dock_cam: 'dock_cam',
    },
  },
  spot: {
    actuators: {
      fl_hx: 'fl_hx',
      fl_hy: 'fl_hy',
      fl_kn: 'fl_kn',
      fr_hx: 'fr_hx',
      fr_hy: 'fr_hy',
      fr_kn: 'fr_kn',
      hl_hx: 'hl_hx',
      hl_hy: 'hl_hy',
      hl_kn: 'hl_kn',
      hr_hx: 'hr_hx',
      hr_hy: 'hr_hy',
      hr_kn: 'hr_kn',
    },
    sensors: {},
    bodies: {
      body: 'body',
      fl_hip: 'fl_hip',
      fl_lleg: 'fl_lleg',
      fl_uleg: 'fl_uleg',
      fr_hip: 'fr_hip',
      fr_lleg: 'fr_lleg',
      fr_uleg: 'fr_uleg',
      hl_hip: 'hl_hip',
      hl_lleg: 'hl_lleg',
      hl_uleg: 'hl_uleg',
      hr_hip: 'hr_hip',
      hr_lleg: 'hr_lleg',
      hr_uleg: 'hr_uleg',
    },
    joints: {
      fl_hx: 'fl_hx',
      fl_hy: 'fl_hy',
      fl_kn: 'fl_kn',
      fr_hx: 'fr_hx',
      fr_hy: 'fr_hy',
      fr_kn: 'fr_kn',
      hl_hx: 'hl_hx',
      hl_hy: 'hl_hy',
      hl_kn: 'hl_kn',
      hr_hx: 'hr_hx',
      hr_hy: 'hr_hy',
      hr_kn: 'hr_kn',
    },
    sites: {},
    geoms: {
      FL: 'FL',
      floor: 'floor',
      FR: 'FR',
      HL: 'HL',
      HR: 'HR',
    },
    keyframes: {
      home: 'home',
    },
    cameras: {},
  },
  g1: {
    actuators: {
      left_ankle_pitch_joint: 'left_ankle_pitch_joint',
      left_ankle_roll_joint: 'left_ankle_roll_joint',
      left_elbow_joint: 'left_elbow_joint',
      left_hip_pitch_joint: 'left_hip_pitch_joint',
      left_hip_roll_joint: 'left_hip_roll_joint',
      left_hip_yaw_joint: 'left_hip_yaw_joint',
      left_knee_joint: 'left_knee_joint',
      left_shoulder_pitch_joint: 'left_shoulder_pitch_joint',
      left_shoulder_roll_joint: 'left_shoulder_roll_joint',
      left_shoulder_yaw_joint: 'left_shoulder_yaw_joint',
      left_wrist_pitch_joint: 'left_wrist_pitch_joint',
      left_wrist_roll_joint: 'left_wrist_roll_joint',
      left_wrist_yaw_joint: 'left_wrist_yaw_joint',
      right_ankle_pitch_joint: 'right_ankle_pitch_joint',
      right_ankle_roll_joint: 'right_ankle_roll_joint',
      right_elbow_joint: 'right_elbow_joint',
      right_hip_pitch_joint: 'right_hip_pitch_joint',
      right_hip_roll_joint: 'right_hip_roll_joint',
      right_hip_yaw_joint: 'right_hip_yaw_joint',
      right_knee_joint: 'right_knee_joint',
      right_shoulder_pitch_joint: 'right_shoulder_pitch_joint',
      right_shoulder_roll_joint: 'right_shoulder_roll_joint',
      right_shoulder_yaw_joint: 'right_shoulder_yaw_joint',
      right_wrist_pitch_joint: 'right_wrist_pitch_joint',
      right_wrist_roll_joint: 'right_wrist_roll_joint',
      right_wrist_yaw_joint: 'right_wrist_yaw_joint',
      waist_pitch_joint: 'waist_pitch_joint',
      waist_roll_joint: 'waist_roll_joint',
      waist_yaw_joint: 'waist_yaw_joint',
    },
    sensors: {
      'imu-pelvis-angular-velocity': 'imu-pelvis-angular-velocity',
      'imu-pelvis-linear-acceleration': 'imu-pelvis-linear-acceleration',
      'imu-torso-angular-velocity': 'imu-torso-angular-velocity',
      'imu-torso-linear-acceleration': 'imu-torso-linear-acceleration',
    },
    bodies: {
      left_ankle_pitch_link: 'left_ankle_pitch_link',
      left_ankle_roll_link: 'left_ankle_roll_link',
      left_elbow_link: 'left_elbow_link',
      left_hip_pitch_link: 'left_hip_pitch_link',
      left_hip_roll_link: 'left_hip_roll_link',
      left_hip_yaw_link: 'left_hip_yaw_link',
      left_knee_link: 'left_knee_link',
      left_shoulder_pitch_link: 'left_shoulder_pitch_link',
      left_shoulder_roll_link: 'left_shoulder_roll_link',
      left_shoulder_yaw_link: 'left_shoulder_yaw_link',
      left_wrist_pitch_link: 'left_wrist_pitch_link',
      left_wrist_roll_link: 'left_wrist_roll_link',
      left_wrist_yaw_link: 'left_wrist_yaw_link',
      pelvis: 'pelvis',
      right_ankle_pitch_link: 'right_ankle_pitch_link',
      right_ankle_roll_link: 'right_ankle_roll_link',
      right_elbow_link: 'right_elbow_link',
      right_hip_pitch_link: 'right_hip_pitch_link',
      right_hip_roll_link: 'right_hip_roll_link',
      right_hip_yaw_link: 'right_hip_yaw_link',
      right_knee_link: 'right_knee_link',
      right_shoulder_pitch_link: 'right_shoulder_pitch_link',
      right_shoulder_roll_link: 'right_shoulder_roll_link',
      right_shoulder_yaw_link: 'right_shoulder_yaw_link',
      right_wrist_pitch_link: 'right_wrist_pitch_link',
      right_wrist_roll_link: 'right_wrist_roll_link',
      right_wrist_yaw_link: 'right_wrist_yaw_link',
      torso_link: 'torso_link',
      waist_roll_link: 'waist_roll_link',
      waist_yaw_link: 'waist_yaw_link',
    },
    joints: {
      left_ankle_pitch_joint: 'left_ankle_pitch_joint',
      left_ankle_roll_joint: 'left_ankle_roll_joint',
      left_elbow_joint: 'left_elbow_joint',
      left_hip_pitch_joint: 'left_hip_pitch_joint',
      left_hip_roll_joint: 'left_hip_roll_joint',
      left_hip_yaw_joint: 'left_hip_yaw_joint',
      left_knee_joint: 'left_knee_joint',
      left_shoulder_pitch_joint: 'left_shoulder_pitch_joint',
      left_shoulder_roll_joint: 'left_shoulder_roll_joint',
      left_shoulder_yaw_joint: 'left_shoulder_yaw_joint',
      left_wrist_pitch_joint: 'left_wrist_pitch_joint',
      left_wrist_roll_joint: 'left_wrist_roll_joint',
      left_wrist_yaw_joint: 'left_wrist_yaw_joint',
      right_ankle_pitch_joint: 'right_ankle_pitch_joint',
      right_ankle_roll_joint: 'right_ankle_roll_joint',
      right_elbow_joint: 'right_elbow_joint',
      right_hip_pitch_joint: 'right_hip_pitch_joint',
      right_hip_roll_joint: 'right_hip_roll_joint',
      right_hip_yaw_joint: 'right_hip_yaw_joint',
      right_knee_joint: 'right_knee_joint',
      right_shoulder_pitch_joint: 'right_shoulder_pitch_joint',
      right_shoulder_roll_joint: 'right_shoulder_roll_joint',
      right_shoulder_yaw_joint: 'right_shoulder_yaw_joint',
      right_wrist_pitch_joint: 'right_wrist_pitch_joint',
      right_wrist_roll_joint: 'right_wrist_roll_joint',
      right_wrist_yaw_joint: 'right_wrist_yaw_joint',
      waist_pitch_joint: 'waist_pitch_joint',
      waist_roll_joint: 'waist_roll_joint',
      waist_yaw_joint: 'waist_yaw_joint',
    },
    sites: {
      imu_in_pelvis: 'imu_in_pelvis',
      imu_in_torso: 'imu_in_torso',
      left_foot: 'left_foot',
      right_foot: 'right_foot',
    },
    geoms: {
      floor: 'floor',
    },
    keyframes: {
      stand: 'stand',
    },
    cameras: {},
  },
};

registerRobotResources(generatedRobotResources);

declare module 'mujoco-react' {
  interface Register {
    robots: {
      franka: {
        actuators: 'actuator1' | 'actuator2' | 'actuator3' | 'actuator4' | 'actuator5' | 'actuator6' | 'actuator7' | 'gripper';
        sensors: never;
        bodies: 'hand' | 'left_finger' | 'link0' | 'link1' | 'link2' | 'link3' | 'link4' | 'link5' | 'link6' | 'link7' | 'right_finger';
        joints: 'finger_joint1' | 'finger_joint2' | 'joint1' | 'joint2' | 'joint3' | 'joint4' | 'joint5' | 'joint6' | 'joint7';
        sites: 'tcp';
        geoms: 'floor';
        keyframes: 'home';
        cameras: never;
      };
      so101: {
        actuators: 'elbow_flex' | 'gripper' | 'shoulder_lift' | 'shoulder_pan' | 'wrist_flex' | 'wrist_roll';
        sensors: never;
        bodies: 'base' | 'camera_mount' | 'gripper' | 'lower_arm' | 'moving_jaw_so101_v1' | 'shoulder' | 'upper_arm' | 'wrist';
        joints: 'elbow_flex' | 'gripper' | 'shoulder_lift' | 'shoulder_pan' | 'wrist_flex' | 'wrist_roll';
        sites: 'baseframe' | 'gripperframe';
        geoms: 'camera_box1' | 'camera_box2' | 'fixed_jaw_box1' | 'fixed_jaw_box2' | 'fixed_jaw_box3' | 'fixed_jaw_box4' | 'fixed_jaw_box5' | 'fixed_jaw_box6' | 'fixed_jaw_box7' | 'fixed_jaw_sph_tip1' | 'fixed_jaw_sph_tip2' | 'fixed_jaw_sph_tip3' | 'moving_jaw_box1' | 'moving_jaw_box2' | 'moving_jaw_box3' | 'moving_jaw_sph_tip1' | 'moving_jaw_sph_tip2' | 'moving_jaw_sph_tip3';
        keyframes: never;
        cameras: 'wrist_cam';
      };
      xlerobot: {
        actuators: 'Elbow_L' | 'Elbow_R' | 'forward' | 'head_pan' | 'head_tilt' | 'Jaw_L' | 'Jaw_R' | 'Pitch_L' | 'Pitch_R' | 'Rotation_L' | 'Rotation_R' | 'turn' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
        sensors: never;
        bodies: 'Base' | 'Base_2' | 'chassis' | 'Fixed_Jaw' | 'Fixed_Jaw_2' | 'head_pan_link' | 'head_tilt_link' | 'Left_Arm_Camera' | 'left_wheel' | 'Lower_Arm' | 'Lower_Arm_2' | 'Moving_Jaw' | 'Moving_Jaw_2' | 'Right_Arm_Camera' | 'right_wheel' | 'Rotation_Pitch' | 'Rotation_Pitch_2' | 'top_base_link' | 'Upper_Arm' | 'Upper_Arm_2' | 'Wrist_Pitch_Roll' | 'Wrist_Pitch_Roll_2';
        joints: 'Elbow_L' | 'Elbow_R' | 'head_pan_joint' | 'head_tilt_joint' | 'Jaw_L' | 'Jaw_R' | 'left_wheel_joint' | 'Pitch_L' | 'Pitch_R' | 'right_wheel_joint' | 'Rotation_L' | 'Rotation_R' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
        sites: never;
        geoms: 'back_caster' | 'front_caster';
        keyframes: never;
        cameras: 'dock_cam';
      };
      spot: {
        actuators: 'fl_hx' | 'fl_hy' | 'fl_kn' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn';
        sensors: never;
        bodies: 'body' | 'fl_hip' | 'fl_lleg' | 'fl_uleg' | 'fr_hip' | 'fr_lleg' | 'fr_uleg' | 'hl_hip' | 'hl_lleg' | 'hl_uleg' | 'hr_hip' | 'hr_lleg' | 'hr_uleg';
        joints: 'fl_hx' | 'fl_hy' | 'fl_kn' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn';
        sites: never;
        geoms: 'FL' | 'floor' | 'FR' | 'HL' | 'HR';
        keyframes: 'home';
        cameras: never;
      };
      g1: {
        actuators: 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint';
        sensors: 'imu-pelvis-angular-velocity' | 'imu-pelvis-linear-acceleration' | 'imu-torso-angular-velocity' | 'imu-torso-linear-acceleration';
        bodies: 'left_ankle_pitch_link' | 'left_ankle_roll_link' | 'left_elbow_link' | 'left_hip_pitch_link' | 'left_hip_roll_link' | 'left_hip_yaw_link' | 'left_knee_link' | 'left_shoulder_pitch_link' | 'left_shoulder_roll_link' | 'left_shoulder_yaw_link' | 'left_wrist_pitch_link' | 'left_wrist_roll_link' | 'left_wrist_yaw_link' | 'pelvis' | 'right_ankle_pitch_link' | 'right_ankle_roll_link' | 'right_elbow_link' | 'right_hip_pitch_link' | 'right_hip_roll_link' | 'right_hip_yaw_link' | 'right_knee_link' | 'right_shoulder_pitch_link' | 'right_shoulder_roll_link' | 'right_shoulder_yaw_link' | 'right_wrist_pitch_link' | 'right_wrist_roll_link' | 'right_wrist_yaw_link' | 'torso_link' | 'waist_roll_link' | 'waist_yaw_link';
        joints: 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint';
        sites: 'imu_in_pelvis' | 'imu_in_torso' | 'left_foot' | 'right_foot';
        geoms: 'floor';
        keyframes: 'stand';
        cameras: never;
      };
    };
    actuators: 'actuator1' | 'actuator2' | 'actuator3' | 'actuator4' | 'actuator5' | 'actuator6' | 'actuator7' | 'elbow_flex' | 'Elbow_L' | 'Elbow_R' | 'fl_hx' | 'fl_hy' | 'fl_kn' | 'forward' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'gripper' | 'head_pan' | 'head_tilt' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn' | 'Jaw_L' | 'Jaw_R' | 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'Pitch_L' | 'Pitch_R' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'Rotation_L' | 'Rotation_R' | 'shoulder_lift' | 'shoulder_pan' | 'turn' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint' | 'wrist_flex' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'wrist_roll' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
    sensors: 'imu-pelvis-angular-velocity' | 'imu-pelvis-linear-acceleration' | 'imu-torso-angular-velocity' | 'imu-torso-linear-acceleration';
    bodies: 'base' | 'Base' | 'Base_2' | 'body' | 'camera_mount' | 'chassis' | 'Fixed_Jaw' | 'Fixed_Jaw_2' | 'fl_hip' | 'fl_lleg' | 'fl_uleg' | 'fr_hip' | 'fr_lleg' | 'fr_uleg' | 'gripper' | 'hand' | 'head_pan_link' | 'head_tilt_link' | 'hl_hip' | 'hl_lleg' | 'hl_uleg' | 'hr_hip' | 'hr_lleg' | 'hr_uleg' | 'left_ankle_pitch_link' | 'left_ankle_roll_link' | 'Left_Arm_Camera' | 'left_elbow_link' | 'left_finger' | 'left_hip_pitch_link' | 'left_hip_roll_link' | 'left_hip_yaw_link' | 'left_knee_link' | 'left_shoulder_pitch_link' | 'left_shoulder_roll_link' | 'left_shoulder_yaw_link' | 'left_wheel' | 'left_wrist_pitch_link' | 'left_wrist_roll_link' | 'left_wrist_yaw_link' | 'link0' | 'link1' | 'link2' | 'link3' | 'link4' | 'link5' | 'link6' | 'link7' | 'lower_arm' | 'Lower_Arm' | 'Lower_Arm_2' | 'Moving_Jaw' | 'Moving_Jaw_2' | 'moving_jaw_so101_v1' | 'pelvis' | 'right_ankle_pitch_link' | 'right_ankle_roll_link' | 'Right_Arm_Camera' | 'right_elbow_link' | 'right_finger' | 'right_hip_pitch_link' | 'right_hip_roll_link' | 'right_hip_yaw_link' | 'right_knee_link' | 'right_shoulder_pitch_link' | 'right_shoulder_roll_link' | 'right_shoulder_yaw_link' | 'right_wheel' | 'right_wrist_pitch_link' | 'right_wrist_roll_link' | 'right_wrist_yaw_link' | 'Rotation_Pitch' | 'Rotation_Pitch_2' | 'shoulder' | 'top_base_link' | 'torso_link' | 'upper_arm' | 'Upper_Arm' | 'Upper_Arm_2' | 'waist_roll_link' | 'waist_yaw_link' | 'wrist' | 'Wrist_Pitch_Roll' | 'Wrist_Pitch_Roll_2';
    joints: 'elbow_flex' | 'Elbow_L' | 'Elbow_R' | 'finger_joint1' | 'finger_joint2' | 'fl_hx' | 'fl_hy' | 'fl_kn' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'gripper' | 'head_pan_joint' | 'head_tilt_joint' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn' | 'Jaw_L' | 'Jaw_R' | 'joint1' | 'joint2' | 'joint3' | 'joint4' | 'joint5' | 'joint6' | 'joint7' | 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wheel_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'Pitch_L' | 'Pitch_R' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wheel_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'Rotation_L' | 'Rotation_R' | 'shoulder_lift' | 'shoulder_pan' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint' | 'wrist_flex' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'wrist_roll' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
    sites: 'baseframe' | 'gripperframe' | 'imu_in_pelvis' | 'imu_in_torso' | 'left_foot' | 'right_foot' | 'tcp';
    geoms: 'back_caster' | 'camera_box1' | 'camera_box2' | 'fixed_jaw_box1' | 'fixed_jaw_box2' | 'fixed_jaw_box3' | 'fixed_jaw_box4' | 'fixed_jaw_box5' | 'fixed_jaw_box6' | 'fixed_jaw_box7' | 'fixed_jaw_sph_tip1' | 'fixed_jaw_sph_tip2' | 'fixed_jaw_sph_tip3' | 'FL' | 'floor' | 'FR' | 'front_caster' | 'HL' | 'HR' | 'moving_jaw_box1' | 'moving_jaw_box2' | 'moving_jaw_box3' | 'moving_jaw_sph_tip1' | 'moving_jaw_sph_tip2' | 'moving_jaw_sph_tip3';
    keyframes: 'home' | 'stand';
    cameras: 'dock_cam' | 'wrist_cam';
  }

  export namespace RobotActuators {
    export type franka = RobotResource<'franka', 'actuators'>;
    export type so101 = RobotResource<'so101', 'actuators'>;
    export type xlerobot = RobotResource<'xlerobot', 'actuators'>;
    export type spot = RobotResource<'spot', 'actuators'>;
    export type g1 = RobotResource<'g1', 'actuators'>;
  }

  export namespace RobotSensors {
    export type franka = RobotResource<'franka', 'sensors'>;
    export type so101 = RobotResource<'so101', 'sensors'>;
    export type xlerobot = RobotResource<'xlerobot', 'sensors'>;
    export type spot = RobotResource<'spot', 'sensors'>;
    export type g1 = RobotResource<'g1', 'sensors'>;
  }

  export namespace RobotBodies {
    export type franka = RobotResource<'franka', 'bodies'>;
    export type so101 = RobotResource<'so101', 'bodies'>;
    export type xlerobot = RobotResource<'xlerobot', 'bodies'>;
    export type spot = RobotResource<'spot', 'bodies'>;
    export type g1 = RobotResource<'g1', 'bodies'>;
  }

  export namespace RobotJoints {
    export type franka = RobotResource<'franka', 'joints'>;
    export type so101 = RobotResource<'so101', 'joints'>;
    export type xlerobot = RobotResource<'xlerobot', 'joints'>;
    export type spot = RobotResource<'spot', 'joints'>;
    export type g1 = RobotResource<'g1', 'joints'>;
  }

  export namespace RobotSites {
    export type franka = RobotResource<'franka', 'sites'>;
    export type so101 = RobotResource<'so101', 'sites'>;
    export type xlerobot = RobotResource<'xlerobot', 'sites'>;
    export type spot = RobotResource<'spot', 'sites'>;
    export type g1 = RobotResource<'g1', 'sites'>;
  }

  export namespace RobotGeoms {
    export type franka = RobotResource<'franka', 'geoms'>;
    export type so101 = RobotResource<'so101', 'geoms'>;
    export type xlerobot = RobotResource<'xlerobot', 'geoms'>;
    export type spot = RobotResource<'spot', 'geoms'>;
    export type g1 = RobotResource<'g1', 'geoms'>;
  }

  export namespace RobotKeyframes {
    export type franka = RobotResource<'franka', 'keyframes'>;
    export type so101 = RobotResource<'so101', 'keyframes'>;
    export type xlerobot = RobotResource<'xlerobot', 'keyframes'>;
    export type spot = RobotResource<'spot', 'keyframes'>;
    export type g1 = RobotResource<'g1', 'keyframes'>;
  }

  export namespace RobotCameras {
    export type franka = RobotResource<'franka', 'cameras'>;
    export type so101 = RobotResource<'so101', 'cameras'>;
    export type xlerobot = RobotResource<'xlerobot', 'cameras'>;
    export type spot = RobotResource<'spot', 'cameras'>;
    export type g1 = RobotResource<'g1', 'cameras'>;
  }

}
