// Auto-generated by mujoco-react. Do not edit.
// Regenerate by running Vite with the mujocoReact() plugin or `mujoco-react codegen`.

import 'mujoco-react';

declare module 'mujoco-react' {
  interface Register {
    robots: {
      franka: {
        actuators: 'actuator1' | 'actuator2' | 'actuator3' | 'actuator4' | 'actuator5' | 'actuator6' | 'actuator7' | 'gripper';
        sensors: never;
        bodies: 'hand' | 'left_finger' | 'link0' | 'link1' | 'link2' | 'link3' | 'link4' | 'link5' | 'link6' | 'link7' | 'right_finger';
        joints: 'finger_joint1' | 'finger_joint2' | 'joint1' | 'joint2' | 'joint3' | 'joint4' | 'joint5' | 'joint6' | 'joint7';
        sites: 'tcp';
        geoms: 'floor';
        keyframes: 'home';
      };
      so101: {
        actuators: 'Elbow' | 'Jaw' | 'Pitch' | 'Rotation' | 'Wrist_Pitch' | 'Wrist_Roll';
        sensors: never;
        bodies: 'Base' | 'Camera' | 'Fixed_Jaw' | 'Lower_Arm' | 'Moving_Jaw' | 'Rotation_Pitch' | 'Upper_Arm' | 'Wrist_Pitch_Roll';
        joints: 'Elbow' | 'Jaw' | 'Pitch' | 'Rotation' | 'Wrist_Pitch' | 'Wrist_Roll';
        sites: 'tcp';
        geoms: never;
        keyframes: 'home';
      };
      xlerobot: {
        actuators: 'Elbow_L' | 'Elbow_R' | 'forward' | 'head_pan' | 'head_tilt' | 'Jaw_L' | 'Jaw_R' | 'Pitch_L' | 'Pitch_R' | 'Rotation_L' | 'Rotation_R' | 'turn' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
        sensors: never;
        bodies: 'Base' | 'Base_2' | 'chassis' | 'Fixed_Jaw' | 'Fixed_Jaw_2' | 'head_camera_depth_frame' | 'head_camera_link' | 'head_camera_rgb_frame' | 'head_pan_link' | 'head_tilt_link' | 'Left_Arm_Camera' | 'left_wheel' | 'Lower_Arm' | 'Lower_Arm_2' | 'Moving_Jaw' | 'Moving_Jaw_2' | 'Right_Arm_Camera' | 'right_wheel' | 'Rotation_Pitch' | 'Rotation_Pitch_2' | 'top_base_link' | 'Upper_Arm' | 'Upper_Arm_2' | 'Wrist_Pitch_Roll' | 'Wrist_Pitch_Roll_2';
        joints: 'Elbow_L' | 'Elbow_R' | 'head_pan_joint' | 'head_tilt_joint' | 'Jaw_L' | 'Jaw_R' | 'left_wheel_joint' | 'Pitch_L' | 'Pitch_R' | 'right_wheel_joint' | 'Rotation_L' | 'Rotation_R' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
        sites: 'head_camera_depth_optical_frame' | 'head_camera_rgb_optical_frame';
        geoms: 'back_caster' | 'front_caster';
        keyframes: never;
      };
      spot: {
        actuators: 'fl_hx' | 'fl_hy' | 'fl_kn' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn';
        sensors: never;
        bodies: 'body' | 'fl_hip' | 'fl_lleg' | 'fl_uleg' | 'fr_hip' | 'fr_lleg' | 'fr_uleg' | 'hl_hip' | 'hl_lleg' | 'hl_uleg' | 'hr_hip' | 'hr_lleg' | 'hr_uleg';
        joints: 'fl_hx' | 'fl_hy' | 'fl_kn' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn';
        sites: never;
        geoms: 'FL' | 'floor' | 'FR' | 'HL' | 'HR';
        keyframes: 'home';
      };
      g1: {
        actuators: 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint';
        sensors: 'imu-pelvis-angular-velocity' | 'imu-pelvis-linear-acceleration' | 'imu-torso-angular-velocity' | 'imu-torso-linear-acceleration';
        bodies: 'left_ankle_pitch_link' | 'left_ankle_roll_link' | 'left_elbow_link' | 'left_hip_pitch_link' | 'left_hip_roll_link' | 'left_hip_yaw_link' | 'left_knee_link' | 'left_shoulder_pitch_link' | 'left_shoulder_roll_link' | 'left_shoulder_yaw_link' | 'left_wrist_pitch_link' | 'left_wrist_roll_link' | 'left_wrist_yaw_link' | 'pelvis' | 'right_ankle_pitch_link' | 'right_ankle_roll_link' | 'right_elbow_link' | 'right_hip_pitch_link' | 'right_hip_roll_link' | 'right_hip_yaw_link' | 'right_knee_link' | 'right_shoulder_pitch_link' | 'right_shoulder_roll_link' | 'right_shoulder_yaw_link' | 'right_wrist_pitch_link' | 'right_wrist_roll_link' | 'right_wrist_yaw_link' | 'torso_link' | 'waist_roll_link' | 'waist_yaw_link';
        joints: 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint';
        sites: 'imu_in_pelvis' | 'imu_in_torso' | 'left_foot' | 'right_foot';
        geoms: 'floor';
        keyframes: 'stand';
      };
    };
    actuators: 'actuator1' | 'actuator2' | 'actuator3' | 'actuator4' | 'actuator5' | 'actuator6' | 'actuator7' | 'Elbow' | 'Elbow_L' | 'Elbow_R' | 'fl_hx' | 'fl_hy' | 'fl_kn' | 'forward' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'gripper' | 'head_pan' | 'head_tilt' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn' | 'Jaw' | 'Jaw_L' | 'Jaw_R' | 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'Pitch' | 'Pitch_L' | 'Pitch_R' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'Rotation' | 'Rotation_L' | 'Rotation_R' | 'turn' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint' | 'Wrist_Pitch' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'Wrist_Roll' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
    sensors: 'imu-pelvis-angular-velocity' | 'imu-pelvis-linear-acceleration' | 'imu-torso-angular-velocity' | 'imu-torso-linear-acceleration';
    bodies: 'Base' | 'Base_2' | 'body' | 'Camera' | 'chassis' | 'Fixed_Jaw' | 'Fixed_Jaw_2' | 'fl_hip' | 'fl_lleg' | 'fl_uleg' | 'fr_hip' | 'fr_lleg' | 'fr_uleg' | 'hand' | 'head_camera_depth_frame' | 'head_camera_link' | 'head_camera_rgb_frame' | 'head_pan_link' | 'head_tilt_link' | 'hl_hip' | 'hl_lleg' | 'hl_uleg' | 'hr_hip' | 'hr_lleg' | 'hr_uleg' | 'left_ankle_pitch_link' | 'left_ankle_roll_link' | 'Left_Arm_Camera' | 'left_elbow_link' | 'left_finger' | 'left_hip_pitch_link' | 'left_hip_roll_link' | 'left_hip_yaw_link' | 'left_knee_link' | 'left_shoulder_pitch_link' | 'left_shoulder_roll_link' | 'left_shoulder_yaw_link' | 'left_wheel' | 'left_wrist_pitch_link' | 'left_wrist_roll_link' | 'left_wrist_yaw_link' | 'link0' | 'link1' | 'link2' | 'link3' | 'link4' | 'link5' | 'link6' | 'link7' | 'Lower_Arm' | 'Lower_Arm_2' | 'Moving_Jaw' | 'Moving_Jaw_2' | 'pelvis' | 'right_ankle_pitch_link' | 'right_ankle_roll_link' | 'Right_Arm_Camera' | 'right_elbow_link' | 'right_finger' | 'right_hip_pitch_link' | 'right_hip_roll_link' | 'right_hip_yaw_link' | 'right_knee_link' | 'right_shoulder_pitch_link' | 'right_shoulder_roll_link' | 'right_shoulder_yaw_link' | 'right_wheel' | 'right_wrist_pitch_link' | 'right_wrist_roll_link' | 'right_wrist_yaw_link' | 'Rotation_Pitch' | 'Rotation_Pitch_2' | 'top_base_link' | 'torso_link' | 'Upper_Arm' | 'Upper_Arm_2' | 'waist_roll_link' | 'waist_yaw_link' | 'Wrist_Pitch_Roll' | 'Wrist_Pitch_Roll_2';
    joints: 'Elbow' | 'Elbow_L' | 'Elbow_R' | 'finger_joint1' | 'finger_joint2' | 'fl_hx' | 'fl_hy' | 'fl_kn' | 'fr_hx' | 'fr_hy' | 'fr_kn' | 'head_pan_joint' | 'head_tilt_joint' | 'hl_hx' | 'hl_hy' | 'hl_kn' | 'hr_hx' | 'hr_hy' | 'hr_kn' | 'Jaw' | 'Jaw_L' | 'Jaw_R' | 'joint1' | 'joint2' | 'joint3' | 'joint4' | 'joint5' | 'joint6' | 'joint7' | 'left_ankle_pitch_joint' | 'left_ankle_roll_joint' | 'left_elbow_joint' | 'left_hip_pitch_joint' | 'left_hip_roll_joint' | 'left_hip_yaw_joint' | 'left_knee_joint' | 'left_shoulder_pitch_joint' | 'left_shoulder_roll_joint' | 'left_shoulder_yaw_joint' | 'left_wheel_joint' | 'left_wrist_pitch_joint' | 'left_wrist_roll_joint' | 'left_wrist_yaw_joint' | 'Pitch' | 'Pitch_L' | 'Pitch_R' | 'right_ankle_pitch_joint' | 'right_ankle_roll_joint' | 'right_elbow_joint' | 'right_hip_pitch_joint' | 'right_hip_roll_joint' | 'right_hip_yaw_joint' | 'right_knee_joint' | 'right_shoulder_pitch_joint' | 'right_shoulder_roll_joint' | 'right_shoulder_yaw_joint' | 'right_wheel_joint' | 'right_wrist_pitch_joint' | 'right_wrist_roll_joint' | 'right_wrist_yaw_joint' | 'Rotation' | 'Rotation_L' | 'Rotation_R' | 'waist_pitch_joint' | 'waist_roll_joint' | 'waist_yaw_joint' | 'Wrist_Pitch' | 'Wrist_Pitch_L' | 'Wrist_Pitch_R' | 'Wrist_Roll' | 'Wrist_Roll_L' | 'Wrist_Roll_R';
    sites: 'head_camera_depth_optical_frame' | 'head_camera_rgb_optical_frame' | 'imu_in_pelvis' | 'imu_in_torso' | 'left_foot' | 'right_foot' | 'tcp';
    geoms: 'back_caster' | 'FL' | 'floor' | 'FR' | 'front_caster' | 'HL' | 'HR';
    keyframes: 'home' | 'stand';
  }
}
